#new workflow

name: Smart Device Tests

on:
  push:
    paths:
      - 'smart_device.py'
      - 'test_smart_device.py'
      - '.github/workflows/**'
  pull_request:
    paths:
      - 'smart_device.py'
      - 'test_smart_device.py'
      - '.github/workflows/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Pythonic
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m pytest test_smart_device.py -v